Power BI Usage Tracking Measure =
// todo: 
// handle all special characters, not just spaces
// handle schema errors in optional parameters


// **SETUP** Fill Out these Variables with your information
//The output is a URL so special characters aren't allowed. but the code automatically cleans spaces, so you don't have to worry about that

// **REQUIRED**: Report Tracking
VAR	ReportName = "YourReportNameHere"
VAR ReportOwnerContact = "myalias@microsoft.com" // Can be group alias
VAR PrimaryDataSource = "YourDataSourceNameHere"
// End Required Setup

// **OPTIONAL**: State Tracking

// Report Page or bookmark state
// This Variable uses the SELECTEDVALUE to determine which row of a table called "ReportState" is selected in the current context. 
// If you create a table with this name and then filter each report page or bookmark to the coresponding value, the tracker will track that. 
// If you leave as is, you will only track report usage and not page usage


VAR ReportPageState = 
	IFERROR(
		SelectedValue('ReportState'[State],"Other State"),
		"NotTracked"
	)

// Data Refresh Metadata. If you have a table that lists the date of refresh/most recent data in your data source, you can include a single data object here.
// The example here is how you would query the MSA Data Analytics Platform's meta datatable.

Var RefreshMetadata =
	IFERROR(
		FORMAT(CALCULATE(SELECTEDVALUE('Data Freshness'[Freshness]),'Data Freshness'[Entity]="FactMonthlyRevenue"),"yyyy-mm-dd"),
		"1900-01-01"
	)

// Similar to page state, you can track the filter context of as many fields  as you like. The context will be output as a list object to the Usage DB. 
// Two examples are provided and you can add as many more as you like.
// Replace "ColumnName" Below with Text value you want to return, and replace 'Table'[Column] with the column you are monitoring. 
// 'Table'[Column] Must be a string typed column, not number or date. If you need another type, you can use Format() to convert it to text.


VAR FilterContext1 = 
	"ColumnName" & ":" & 
		IF(ISFILTERED('Table'[Column]),
			SelectedValue('Table'[Column],"More than one value"),
			"NotFiltered"
		),
	"NotTracked:NotTracked"
	
VAR FilterContext2 = 
	"ColumnName" & ":" & 
		IF(ISFILTERED('Table'[Column]),
			SelectedValue('Table'[Column],"More than one value"),
			"NotFiltered"
		),
	"NotTracked:NotTracked"

	
VAR AssembledContextString = FilterContext1 & "|" & FilterContext2

VAR OtherData = "Unused"

// **END SETUP**. Do not change anything below this line

VAR User = USERPRINCIPALNAME()
VAR QueryTime = Format(NOW(),"yyyy-mm-dd_hh:mm")

// This is the base URL for the Flow Trigger that stores the request URL and serves the image back
Var FlowRequestBaseURL = "{GET THIS URL FROM YOUR FLOW}"


// This Assembles the Data Package to send to flow
Var AssembledDataPacakge =
	User & ";" &
	ReportName & ";" & 
	ReportOwnerContact & ";" & 
	PrimaryDataSource & ";" &
	QueryTime & ";" &
	ReportPageState & ";" &
	RefreshMetadata & ";" &
	AssembledContextString & ";" &
	OtherData

// Clean the package for special characters
VAR CleanedDataPackage =
	SUBSTITUTE ( AssembledDataPacakge," ", "_" )

// This is the final URL to send to flow
VAR AssembledURL = 
	SUBSTITUTE(FlowRequestBaseURL, "{Data}", CleanedDataPackage)
	
Return
AssembledURL
